### ISSUE TITLE
R_Small not defined ?

### ISSUE THREAD

**Issue by coliss86** [louckousse/Agathe#2]
Where is `R_small` defined ? 

![image](https://user-images.githubusercontent.com/23615562/95011570-eaf4ad80-0631-11eb-90b8-bbae10f75189.png)

**Comment by coliss86** [comment]
Same question for  `D_small` and `Crystal_GND24_Small`
![image](https://user-images.githubusercontent.com/23615562/95011593-065fb880-0632-11eb-9c3c-1025cd800650.png)

![image](https://user-images.githubusercontent.com/23615562/95011604-12e41100-0632-11eb-9331-42d48fe70d29.png)

**Comment by louckousse** [comment]
It's normal for D_Small and Crystal.
It's an error for the R_Small tho'.

I'll look into it. Thank you.

**Comment by coliss86** [comment]
**Where** is it defined ? ;)

what error did you find for R_Small ?

**Comment by louckousse** [comment]
So, after checking it, I've forgotten the value for the crystal and the resistor according to this [tutorial](https://wiki.ai03.com/books/pcb-design/page/pcb-guide-part-3---creating-the-mcu-schematic). For the diodes, you don't need to change the value and you can leave it at d_small.

Thank you for spotting that.
