### ISSUE TITLE
Lib not found

### ISSUE THREAD

**Issue by coliss86** [louckousse/Agathe#6]
I have this error when opening footprint

![image](https://user-images.githubusercontent.com/23615562/95254741-a418da80-0820-11eb-8d13-b5d4c2be1643.png)

![image](https://user-images.githubusercontent.com/23615562/95253941-6e272680-081f-11eb-8a9d-a001634ab348.png)

**Comment by louckousse** [comment]
I have this error too, I don't know why. I'll look into it one day.

**Comment by louckousse** [comment]
I've merged your PR about the libs, does it correct this issue ?

**Comment by coliss86** [comment]
Hum no :'(
I see that there is a ref to `fancy-kicad-stuff/cc.pretty` in `fp-lib-table`.

Do you need it ? It can be removed otherwisef

**Comment by louckousse** [comment]
It's Christian Clavier ! I'll add it legit

**Comment by coliss86** [comment]
I just update to latest master, another error : 
![image](https://user-images.githubusercontent.com/23615562/95652964-2e00c600-0af5-11eb-8648-96384a3dadda.png)

Hard to fix :'(

**Comment by coliss86** [comment]
Never mind, I didn't update submodules...

**Comment by coliss86** [comment]
But : When I try to open `Agathe-cache.lib`, I still get the following error : 
![image](https://user-images.githubusercontent.com/23615562/95653083-170ea380-0af6-11eb-9860-f377803c9eae.png)

I fixed it with #12
